-- Seed nfl_teams + nfl_stadiums (run once, after the schema, before the aggregate scripts)

insert into nfl_teams (team_abbr, full_name, conference, division, home_stadium) values
('ARI','Arizona Cardinals','NFC','West','ARI'),
('ATL','Atlanta Falcons','NFC','South','ATL'),
('BAL','Baltimore Ravens','AFC','North','BAL'),
('BUF','Buffalo Bills','AFC','East','BUF'),
('CAR','Carolina Panthers','NFC','South','CAR'),
('CHI','Chicago Bears','NFC','North','CHI'),
('CIN','Cincinnati Bengals','AFC','North','CIN'),
('CLE','Cleveland Browns','AFC','North','CLE'),
('DAL','Dallas Cowboys','NFC','East','DAL'),
('DEN','Denver Broncos','AFC','West','DEN'),
('DET','Detroit Lions','NFC','North','DET'),
('GB','Green Bay Packers','NFC','North','GB'),
('HOU','Houston Texans','AFC','South','HOU'),
('IND','Indianapolis Colts','AFC','South','IND'),
('JAX','Jacksonville Jaguars','AFC','South','JAX'),
('KC','Kansas City Chiefs','AFC','West','KC'),
('LV','Las Vegas Raiders','AFC','West','LV'),
('LAC','Los Angeles Chargers','AFC','West','LAC'),
('LAR','Los Angeles Rams','NFC','West','LAR'),
('MIA','Miami Dolphins','AFC','East','MIA'),
('MIN','Minnesota Vikings','NFC','North','MIN'),
('NE','New England Patriots','AFC','East','NE'),
('NO','New Orleans Saints','NFC','South','NO'),
('NYG','New York Giants','NFC','East','NYG'),
('NYJ','New York Jets','AFC','East','NYJ'),
('PHI','Philadelphia Eagles','NFC','East','PHI'),
('PIT','Pittsburgh Steelers','AFC','North','PIT'),
('SEA','Seattle Seahawks','NFC','West','SEA'),
('SF','San Francisco 49ers','NFC','West','SF'),
('TB','Tampa Bay Buccaneers','NFC','South','TB'),
('TEN','Tennessee Titans','AFC','South','TEN'),
('WAS','Washington Commanders','NFC','East','WAS')
on conflict (team_abbr) do nothing;

insert into nfl_stadiums (stadium_key, name, roof, surface, lat, lon, altitude_ft, weather_relevant, tz) values
('ARI','State Farm Stadium','retractable','grass',33.5276,-112.2626,1070,false,'America/Phoenix'),
('ATL','Mercedes-Benz Stadium','retractable','turf',33.7554,-84.4008,1050,false,'America/New_York'),
('BAL','M&T Bank Stadium','outdoor','grass',39.278,-76.6227,33,true,'America/New_York'),
('BUF','Highmark Stadium','outdoor','turf',42.7738,-78.787,600,true,'America/New_York'),
('CAR','Bank of America Stadium','outdoor','turf',35.2258,-80.8528,751,true,'America/New_York'),
('CHI','Soldier Field','outdoor','grass',41.8623,-87.6167,597,true,'America/Chicago'),
('CIN','Paycor Stadium','outdoor','turf',39.0955,-84.5161,490,true,'America/New_York'),
('CLE','Huntington Bank Field','outdoor','grass',41.5061,-81.6995,571,true,'America/New_York'),
('DAL','AT&T Stadium','retractable','turf',32.7473,-97.0945,551,false,'America/Chicago'),
('DEN','Empower Field at Mile High','outdoor','grass',39.7439,-105.0201,5280,true,'America/Denver'),
('DET','Ford Field','dome','turf',42.34,-83.0456,600,false,'America/New_York'),
('GB','Lambeau Field','outdoor','grass',44.5013,-88.0622,640,true,'America/Chicago'),
('HOU','NRG Stadium','retractable','grass',29.6847,-95.4107,49,false,'America/Chicago'),
('IND','Lucas Oil Stadium','retractable','turf',39.7601,-86.1639,715,false,'America/New_York'),
('JAX','EverBank Stadium','outdoor','grass',30.3239,-81.6373,16,true,'America/New_York'),
('KC','GEHA Field at Arrowhead Stadium','outdoor','grass',39.0489,-94.4839,750,true,'America/Chicago'),
('LV','Allegiant Stadium','dome','grass',36.0909,-115.1833,2030,false,'America/Los_Angeles'),
('LAC','SoFi Stadium','dome','turf',33.9535,-118.3392,120,false,'America/Los_Angeles'),
('LAR','SoFi Stadium','dome','turf',33.9535,-118.3392,120,false,'America/Los_Angeles'),
('MIA','Hard Rock Stadium','outdoor','grass',25.958,-80.2389,8,true,'America/New_York'),
('MIN','U.S. Bank Stadium','dome','turf',44.9736,-93.2575,830,false,'America/Chicago'),
('NE','Gillette Stadium','outdoor','turf',42.0909,-71.2643,289,true,'America/New_York'),
('NO','Caesars Superdome','dome','turf',29.9511,-90.0812,3,false,'America/Chicago'),
('NYG','MetLife Stadium','outdoor','turf',40.8135,-74.0745,7,true,'America/New_York'),
('NYJ','MetLife Stadium','outdoor','turf',40.8135,-74.0745,7,true,'America/New_York'),
('PHI','Lincoln Financial Field','outdoor','grass',39.9008,-75.1675,39,true,'America/New_York'),
('PIT','Acrisure Stadium','outdoor','grass',40.4468,-80.0158,728,true,'America/New_York'),
('SEA','Lumen Field','outdoor','turf',47.5952,-122.3316,10,true,'America/Los_Angeles'),
('SF','Levi''s Stadium','outdoor','grass',37.403,-121.9698,13,true,'America/Los_Angeles'),
('TB','Raymond James Stadium','outdoor','grass',27.9759,-82.5033,26,true,'America/New_York'),
('TEN','Nissan Stadium','outdoor','grass',36.1665,-86.7713,385,true,'America/Chicago'),
('WAS','Northwest Stadium','outdoor','grass',38.9077,-76.8645,203,true,'America/New_York')
on conflict (stadium_key) do nothing;
